language: objective-c
osx_image: xcode7.2
xcode_workspace: GrowlMail/GrowlMail.xcworkspace
xcode_scheme: GrowlMail

script:
  - cd GrowlMail
  - xcodebuild -workspace GrowlMail.xcworkspace -scheme GrowlMail build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
